import React from 'react';

const TermsOfServicePage: React.FC = () => {
    return (
        <div className="w-full max-w-4xl mx-auto animate-fade-in-up text-light-text dark:text-cyber-text">
            <div className="text-center mb-12">
                <h2 className="text-4xl sm:text-5xl font-bold text-light-cyan dark:text-cyber-cyan">Terms of Service</h2>
                <p className="mt-4 text-lg text-light-text-secondary dark:text-cyber-text-secondary">
                    Please read these terms carefully before using our service.
                </p>
                <p className="mt-2 text-sm text-light-text-secondary dark:text-cyber-text-secondary/80">Last Updated: {new Date().toLocaleDateString()}</p>
            </div>

            <div className="space-y-8 text-base leading-relaxed text-light-text-secondary dark:text-cyber-text-secondary">
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">1. Acceptance of Terms</h3>
                    <p>
                        By accessing and using Synthetica ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services. Any participation in this service will constitute acceptance of this agreement.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">2. Description of Service</h3>
                    <p>
                        Synthetica provides users with an AI-powered tool to analyze news articles, images, and other content for authenticity. The analysis is generated by an artificial intelligence model and is intended for informational purposes only.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">3. User Responsibilities</h3>
                    <p>
                        You are responsible for your own conduct and content while using the Service. You agree to use the Service only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the Service. You must not submit any content that is illegal, defamatory, or infringes on any third-party rights.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">4. Subscriptions and Payments</h3>
                    <p>
                        Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring and periodic basis ("Billing Cycle"). Billing cycles are set either on a weekly, monthly, or annual basis. At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or we cancel it.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">5. Disclaimer and Limitation of Liability</h3>
                    <p className="font-bold text-light-red dark:text-cyber-red">
                        The analysis provided by Synthetica is generated by an AI model and may contain inaccuracies or errors. It is not a substitute for professional fact-checking or critical thinking. We do not guarantee the accuracy, completeness, or usefulness of any information on the Service. You agree that your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We shall not be liable for any indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">6. Intellectual Property</h3>
                    <p>
                        The Service and its original content, features, and functionality are and will remain the exclusive property of Synthetica and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Synthetica.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">7. Termination</h3>
                    <p>
                        We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
                    </p>
                </section>
                <section>
                    <h3 className="text-2xl font-bold text-light-text dark:text-cyber-text mb-3">8. Changes to Terms</h3>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.
                    </p>
                </section>
            </div>
        </div>
    );
};

export default TermsOfServicePage;